### PR TITLE
feat(replace-menu): allow replacing with plain task

### PR DESCRIPTION
**Pull request by marstamm**
Adds the option to "replace" a templated Task with a plain task. This performs an unlink internally

Recording 2022-04-06 at 14 28 48

### CODE REVIEW

**Review by nikku — COMMENTED** [review]
I think this works good as a workaround. 

What would be great is if the service task element would not sit on top of all entries, but where it normally sits. This way we'd not "promote it". Do you think we can make this happen?

**Comment by marstamm** [comment]
> the service task element would not sit on top of all entries, but where it normally sits

Unfortunately, with our current API, we can only give priority to providers, but not individual entries. So with this solution, it is either on top or at the bottom of the "normal" entries.
I decided for "on top" especially because it promotes it - the top task type keeps all the configuration options that might be lost if the element type is changed to something else

**Comment by nikku** [comment]
In this case, let's ship this as an unblocker. Thanks :clap:

**Comment by nikku** [comment]
Unfortunately this seems to be a victim of https://github.com/camunda/camunda-bpmn-js/issues/87. It does not work in combination with camunda-bpmn-js. :see_no_evil:

**Comment by nikku** [comment]
We have to hook in with a middleware and inject the entry with lower than low priority: https://github.com/camunda/web-modeler/pull/431#issuecomment-1022252847.

**Comment by marstamm** [comment]
Argh, and I wanted it to be nice with a provider rather than just jamming it in at the [ReplaceMenu](https://github.com/bpmn-io/bpmn-js-connectors-extension/blob/master/src/replace-menu/ReplaceMenu.js#L88). That would have worked :see_no_evil:  

Anyhow, I will have a look and try to add it with super-low-priority. I was not aware of the middleware, this might even allow us to add it at the usual place :thinking:

**Pull request merged**
