### PR TITLE
feat: only allow selection of latest versions

### LINKED ISSUE #38: Only allow selecting latest version of templates
__Is your feature request related to a problem? Please describe__

When having multiple verions of the same template (different `version` numbers for templates with the same `id`), the "append connector", "change element" and "choose element template" menus list all versions of the template. This can be confusing as the name and description of the connector can stay the same and there is no other indicator (like version number) for users to distinguish between different versions.

__Describe the solution you'd like__

* When choosing a template to assign to an element, only the latest version of a template is available.
* When creating/appending anything only show latest version of templates
* When replacing, only show latest version of templates

__Describe alternatives you've considered__

We could only pass the latest versions of templates into the extension. However, as the extension also influences which templates are available in the properties panel, this is not a good alternative as it would break diagrams which use older versions of the template. Not having older versions available would lead to a "Template not found" message in the properties panel instead of the desired "Update available"

----

Required by https://github.com/camunda/web-modeler/issues/1183.

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #38

### CODE REVIEW

**Review by nikku — CHANGES_REQUESTED** [review]
For good measure we could add a versioned connector to the [example](https://github.com/bpmn-io/bpmn-js-connectors-extension/tree/master/example/.camunda/element-templates).

This way we can verify, at least manually, that this works.

**Comment by pinussilvestrus** [comment]
Works for me with the following example templates (omitted most content for pasting).

```json
[
  {
    "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
    "name": "Slack: Send Message",
    "id": "io.camunda.connectors.Slack.v1",
    "description": "Send a message to a channel or user",
    "version": 1,
    ...
  },
  {
    "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
    "name": "Slack: Send Message",
    "id": "io.camunda.connectors.Slack.v1",
    "description": "Send a message to a channel or user",
    "version": 2,
    ...
  }
]
```

image

As @nikku proposed, let's add one example to this PR.

**Comment by pinussilvestrus** [comment]
On the sidenote, I detected some errors when trying to open the element templates chooser from the properties panel. I opened an issue for that: https://github.com/bpmn-io/bpmn-js-connectors-extension/issues/43

**Comment by nikku** [comment]
Thanks for the update @Skaiir.

I think it is better to not mix and match the different template cases, hence I've added a dedicated "versioned" template example. Cf. https://github.com/bpmn-io/bpmn-js-connectors-extension/pull/42/commits/6d18ad76a56d303ca5b19b51089f4e51c97e75ac.

**Comment by Skaiir** [comment]
Yeah that makes sense Nico, thanks for taking care of it :)

**Pull request merged**
